name: CI/CD for commonlib.h

on:
  push:
    branches:
      - main


jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pip dependencies
        run: |
          pip install coloredlogs

      - name: Build
        run: |
          sh ./test.sh build -x
  run-job:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pip dependencies
        run: |
          pip install coloredlogs

      - name: Run
        run: |
          sh ./test.sh run -x

